version: "2.0"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: "123456"
  splash:
    image: scrapinghub/splash
    ports:
      - "8050:8050"
  haipproxy:
    build: .
    command: sh run.sh
    volumes:
      - .:/haipproxy
    ports:
      - "3128:3128"
    links:
      - redis
      - splash
